name: config of answer generation for arena-hard-v0.1

bench_name: arena-hard-v0.1

temperature: 0.0
max_tokens: 4096
num_choices: 1

# a list of model to generate answers
model_list:
  # - gpt-3.5-turbo-0125
  # - plato_7b_kto_all_37k_iter1_epoch2_2
  # - plato_7b_kto_all_37k_iter1_epoch2_1
  # - plato_7b_ktomix50k
  # - mixtral_instruct_8x22b
  # - nowllm_mistral_7b_24_03_28_sft_v1_150k_sharegpt_scale
  # - mixtral_instruct_tgi
  # - mistral_7b_selfdist
  # - plato_7b_kto_all_37k_iter0
  # - plato_7b_kto_all_37k_iter1_checkpoint_2344
  # - plato_7b_kto_all_37k_iter2_checkpoint_2346
  # - nowllm_mistral_7b_24_03_28_sft_v1_150k_sharegpt_scale_round2
  - Mixtral_8x7b_04_30_24_exp1
  # - plato_7b_ktomix50k_round2
